name: CI
env:
  APP_NAME  : "FUCK"
  PAC_NAME  : "Fuck-deploy-ver-${{ github.sha }}"


on: 
 push:
  branches:
    - main
jobs:
 my_testing: 
  runs-on: ubuntu-latest 
  
  steps:
   - name: Print Hello
     run: echo "Fuck word"
     
   - name : Fuck my dick
     run: echo "App name:${{ env.APP_NAME }}"
     
   - name: git clone
     uses:  actions/checkout@v1
     
   - name: Testing 
     run: ls -la
 
 my_deploy: 
  runs-on: ubuntu-latest
  needs: [my_testing]
  steps:
   - name: AWS???
     run: aws --version && lsb_release -a
     
   - name: Print Dick
     run: echo "Dick word"
   - name: Cunt
     run: echo "Pac name id ${{ env.PAC_NAME }}"

