name: CI-CDPipeline
env:
  EB_PACKEGE_S3_BUCKET_NAME  : "github-tresh"
  EB_APPLICATION_NAME  : "Fuck"
  EB_ENVIRONMENT_NAME: "Fuck-env-2"
  DEPLOY_PACKEGE_NAME : ""
  AWS_REGION_NAME: "eu-north-1"

on: 
 push:
  branches:
    - main
jobs:
  my-ci-part: 
   runs-on: ubuntu-latest 
  
   steps:
   - name: git clone
     uses:  actions/checkout@v1
     
   - name: Print Hello
     run: echo "Fuck word"
     
 

