name: CI
env:
  APP_NAME  : "FUCK"
  PAC_NAME  : "Fuck-deploy-ver-${{ githab.sha }}"


on: 
 push:
  branches:
    - main
jobs:
 my_testing: 
  runs-on: ubuntu-latest 
  
  steps:
   - name: Print Hello
     run: echo "Fuck word"   
   - name : Fuck my dick
     run: echo "App name: ${{ env.APP_NAME }} "
 
 my_deploy: 
  runs-on: ubuntu-latest
  needs: [my_testing]
  steps:
   - name: Print Dick
     run: echo "Dick word"
   - name: Cunt
     run: echo "Pac name id ${{ env.PAC_NAME }}"

