name: CI


on: 
 push:
  branches:
    - main
jobs:
 my_testing: 
  runs-on: ubuntu-latest 
  
  steps:
   - name: Print Hello
     run: echo "Fuck word"
        
 
 my_deploy: 
  runs-on: ubuntu-latest
  needs: [my_testing]
  steps:
   - name: Print Dick
     run: echo "Dick word"

